#!/usr/bin/env bash
set -euo pipefail

output="REPOSITORY_INDEX.md"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Repository Index"
  echo
  echo "> AUTO-GENERATED FILE — DO NOT EDIT MANUALLY."
  echo "> Generated by GitHub Actions from the repository tree."
  echo
  echo "## Structure"
  echo
  echo '```text'
  find . -type f \
    -not -path './.git/*' \
    -not -path "./$output" \
    | sed 's#^./##' \
    | sort
  echo '```'
} > "$tmp"

if [[ ! -f "$output" ]] || ! cmp -s "$tmp" "$output"; then
  mv "$tmp" "$output"
else
  rm -f "$tmp"
fi
